### ISSUE TITLE
Syllable count syntax producing word with wrong number of syllables

### ISSUE THREAD

**Issue by factormystic** [TheBerkin/Rant#75] opened 2015-07-02 02:16 UTC
Via the sandbox, I ran `<noun(3)>` several times and many results didn't have 3 syllables, for example, `corn` was one output, as well as `globe`, `horn`, and `trunk`. The docs say:

> Using only a without a hyphen means that you'll get an entry that has exactly that number of syllables:

...so this appears to be a bug.

**Comment by TheBerkin** [comment] 2015-07-02 02:38
The sandbox uses [Rantionary](http://github.com/RantLang/Rantionary) for dictionary data. Not all of the entries have pronunciation metadata, and some of it may not be accurate, as it was generated with an algorithm.

If you'd be interested in contributing data for this, we'd happily accept such a pull request.

**Comment by factormystic** [comment] 2015-07-02 13:46
That explanation should probably be added to the docs, so people running snippets from the docs in the sandbox don't get confused and think your app is busted.

**Comment by TheBerkin** [comment] 2015-07-02 15:46
I have modified the rhyming carriers description with a note to make that more clear.

**Comment by TheBerkin** [comment] 2015-07-02 15:59
Closing this since it's technically not a bug with Rant.

**Closed by TheBerkin** 2015-07-02 15:59 UTC
Labels: bug, dictionaries, minor
